- name: print variables
  hosts:  all
  vars:
    URL: www.google.com
  tasks:
    - name: variable checking
      debug:
        msg: output = {{URL}}

## Observation: Vars can be given on play level, Meaning all tasks can access that Variable.
- name: Demo on Task Variables
  hosts:  all
  tasks:
    - name: task variable
      debug:
        msg: output = {{URL}}
      vars:
        URL: www.task.com

## Observation, Variables can be given at task level , Only that task can access that variable.

- name: variables on both level
  hosts: all
  vars:
    URL: vars.google.com
  tasks:
      - name: Print varsiable
        debug:
          msg: URL = {{URL}}
        vars:
          URL: tasks.google.com

## Observation: Variables of tasks will always override the variables of play

- name: Take input from user
  hosts: all
  vars_prompt:
    - name: URL
      prompt: Enter URL
      private: no
  tasks:
    - name: Print URL
      debug:
        msg: URL = {{URL}}

##Take the input from the file level variable

- name: Variables from files
  hosts: all
  vars_files:
    - var01.yaml
  tasks:
    - name: Print variable
      debug:
        msg: URL = {{URL}}

## Observation : Variable Precedence Order , vars_files, vars_prompt, vars
- name: overlap vars with vars_prompt
  hosts: all
  vars_prompt:
    - name: URL
      prompt: Enter URL
      private: no
  vars:
    URL: vars.google.com
  vars_files:
    - var01.yaml
  tasks:
    - name: Print variable
      debug:
        msg: URL = {{URL}}
    - name: Print URL
      debug:
        msg: URL = {{URL}}
      vars:
        URL: tasks.google.com

