- name: print variables
  hosts:  all
  vars:
    URL: www.google.com
  tasks:
    - name: variable checking
      debug:
        msg: output = {{URL}}

## Observation: Vars can be given on play level, Meaning all tasks can access that Variable.
- name: Demo on Task Variables
  hosts:  all
  tasks:
    - name: task variable
      debug:
        msg: output = {{URL}}
      vars:
        URL: www.task.com

## Observation, Variables can be given at task level , Only that task can access that variable.

- name: variables on both level
  hosts: all
  vars:
    URL: vars.google.com
  tasks:
      - name: Print varsiable
        debug:
          msg: URL = {{URL}}
        vars:
          URL: tasks.google.com