- name: Gather_Facts
  hosts:  all
  gather_facts: yes
  tasks:
    - name: testing gather facts
      debug:
        msg:  Hostname = {{ansible_hostname}}

    - name: Print memory
       debug:
         msg:  Memory of the node = {{ansible_memory_mb.real.free}}

